### ISSUE TITLE
【信息查询-口罩预约方式查询】链接过期

### ISSUE THREAD

**Issue by lishuhang** [wertycn/nCoV#20]
## 当前问题

![](https://lishuhang.me/img/2020/03/20200306120401.png)

![](https://lishuhang.me/img/2020/03/20200306120423.png)

## 期待的正确输出

https://ncov.html5.qq.com/mouthmask/index.html?channelid=6

**Comment by wertycn** [comment]
感谢反馈  ~  已更新
