### ISSUE TITLE
能把线上入口做成https的吗

### ISSUE THREAD

**Issue by DrRoad** [wertycn/nCoV#4]

**Comment by wertycn** [comment]
今天会试试部署SSL ， 不过目前图像资源等均为http 混合状态体验更不好

**Comment by scdn** [comment]
https://www.haixiaowen.com/feiyan/index/counts
我做了个https的计数接口

**Comment by scdn** [comment]
数源来源为腾讯新闻
https://news.qq.com/zt2020/page/feiyan.htm

**Comment by wertycn** [comment]
> _No description provided._

已将入口升级为https协议 原有http协议暂时保留   ， 数据接口统一增加了https协议版本  端口2021 ，原有http接口不变

**Comment by wertycn** [comment]
https虽好，但是对性能影响有点大，还是要按需使用， 实测用go服务实现的接口直接配置https对性能下降达到90% 以上 本地QPS从  13000 下降到 1000   ，公网QPS也下降了一半
