### ISSUE TITLE
车次查询

### ISSUE THREAD

**Issue by WeileiZeng** [wertycn/nCoV#5]
http://2019ncov.nosugartech.com/

建议增加车次查询网站

**Comment by wertycn** [comment]
感谢反馈 已添加人民日报推广的查询地址 https://h5.peopleapp.com/txcx/index.html

**Comment by WeileiZeng** [comment]
我发的那个是无糖科技的初始网站，其他各大网站都是嵌套/引用页面。

它本身是开源的，所以也没什么差别。

**Comment by wertycn** [comment]
OK
