### ISSUE TITLE
nav.json建议通过api调用,直接编辑json文件太麻烦

### ISSUE THREAD

**Issue by scdn** [wertycn/nCoV#7]

**Comment by scdn** [comment]
虽然你开放了疫情信息导航数据接口,但是自行编辑很困难

**Comment by wertycn** [comment]
已经有开放的导航数据接口，但是开放接口的数据肯定只能是由我去维护的，对于其他使用本项目的开发者而言，如果想要自定义添加导航数据，开发成本最小的方式还是编辑nav.json文件，最初因为时间原因，我没有将时间花在开发管理系统上，后续会增加一个独立管理系统

**Comment by scdn** [comment]
不用自建cms,使用第三方平台开放的api即可,比如github,语雀,几行代码的事,
我自己已经实现,纯属建议
